### ISSUE TITLE
Incorrect request time logging.

### ISSUE THREAD

**Issue by egochao** [Moesif/moesifasgi#12]
### Issue
We are using moesif analytic to monitor our API. 
But all the elapsed duration of API call show up to be 1-3 mili-second. This number is clearly incorrect since your core internal logging show 1-2 second elapsed. 

After check this repo I found this.
[Here](https://github.com/Moesif/moesifasgi/blob/master/moesifasgi/middleware.py#L154) is the moesif middleware call the API and get the response.
[Here](https://github.com/Moesif/moesifasgi/blob/master/moesifasgi/middleware.py#L166) is where the start time get registered which is after the API have been call. 

Please take a look.

**Comment by praves77** [comment]
Thanks @egochao for reporting this issue - much appreciated. A fix and test is in progress and we would publish next release in a few hours.

**Comment by praves77** [comment]
@egochao We've published fix in release `0.1.3` . Let us know if you still the issue. Thanks.

**Comment by egochao** [comment]
Hi @praves77 
We test the new version and the issues seem to be fixed. 
Thanks for the prompt response.

**Comment by praves77** [comment]
Thanks @egochao for the confirmation. Much appreciated your support in finding and resolving it.
