### ISSUE TITLE
update supported fastapi versions

### ISSUE THREAD

**Issue by jrhizor** [Moesif/moesifasgi#19]
The README shows 0.51.0 - 0.78.0 as the supported versions, but fastapi@0.92.0 has a major security vulnerability.

The library seems to work with even the latest `fastapi@0.108.0` and `moesifasgi@0.1.4`. 

Would it be ok to upgrade the examples and to use more recent fastapi versions and update the listed compatibility?

**Comment by keyur9** [comment]
Hello, @jrhizor! We've updated the dependencies in the example and published the moesifasgi version. Please update to the latest version [pip install --no-cache moesifasgi](https://pypi.org/project/moesifasgi/) and let use know if you still see the issue.
